name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: ./.github/actions/build
      with:
          owm-geo-key: ${{ secrets.OWM_GEO }}
          owm-current-key: ${{ secrets.OWM_CURRENT }}
