name: Release and publish on tag

on:
  push:
    tags:
      - '*.*.*'

jobs:
  release-firefox:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7

    - uses: ./.github/actions/build
      with:
          owm-geo-key: ${{ secrets.OWM_GEO }}
          owm-current-key: ${{ secrets.OWM_CURRENT }}

    - name: Extract release notes
      id: extract-release-notes
      uses: ffurrer2/extract-release-notes@v3

    - name: Create version metadata
      run: |
          release='${{ steps.extract-release-notes.outputs.release_notes }}'
          cat <<EOF > ./version-metadata.json
          {
            "version": {
              "release_notes": {
                "en-US": $(echo "${release//### }" | jq -sR .)
              }
            }
          }
          EOF

    - uses: actions/upload-artifact@v7
      with:
        path: ./version-metadata.json
        name: "version-matadata.json"

    - run: yarn web-ext sign --api-key ${{ secrets.AMO_ISSUER }} --api-secret ${{ secrets.AMO_SECRET }} --channel=listed --source-dir build/firefox --amo-metadata ./version-metadata.json

    - uses: actions/upload-artifact@v7
      with:
        path: web-ext-artifacts/new_tab_moment-${{ github.ref_name }}.xpi
        if-no-files-found: error
        name: new_tab_moment.xpi

    outputs:
      release_notes: ${{ steps.extract-release-notes.outputs.release_notes }}

  release-github:
    needs: [release-firefox]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v8.0.1

      - name: Display structure of downloaded files
        run: ls -R

      - name: Create Release
        uses: softprops/action-gh-release@v3.0.1
        with:
          tag_name: ${{ github.ref }}
          name: ${{ github.ref_name }}
          body: ${{ needs.release-firefox.outputs.release_notes }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            new_tab_moment.zip/new_tab_-_moment-${{ github.ref_name }}.*.zip
            new_tab_moment.xpi/new_tab_moment-${{ github.ref_name }}.xpi

  release-edge:
    needs: [release-firefox]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v8.0.1

      - name: Display structure of downloaded files
        run: ls -R

      - uses: wdzeng/edge-addon@v2.1.1
        with:
          product-id: ${{ secrets.EDGE_PRODUCT }}
          zip-path: new_tab_moment.zip/new_tab_-_moment-${{ github.ref_name }}.edge.zip
          client-id: ${{ secrets.EDGE_CLIENT }}
          api-key: ${{ secrets.EDGE_KEY }}
          access-token-url: ${{ secrets.EDGE_TOKEN_URL }}
