name: Release and publish on tag

on:
  push:
    tags:
      - '*.*.*'

jobs:
  release-firefox:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: ./.github/actions/build
      with:
          owm-geo-key: ${{ secrets.OWM_GEO }}
          owm-current-key: ${{ secrets.OWM_CURRENT }}

    - name: Extract release notes
      id: extract-release-notes
      uses: ffurrer2/extract-release-notes@v1

    - name: Create version metadata
      run: |
          release='${{ steps.extract-release-notes.outputs.release_notes }}'
          cat <<EOF > ./version-metadata.json
          {
            "version": {
              "release_notes": {
                "en-US": $(echo "${release//### }" | jq -sR .),
                "_default": "en-US"
              }
            }
          }EOF

    - uses: actions/upload-artifact@v3
      with:
        path: ./version-metadata.json

    - run: yarn web-ext sign --api-key ${{ secrets.AMO_ISSUER }} --api-secret ${{ secrets.AMO_SECRET }} --use-submission-api --channel=listed --source-dir build --amo-metadata ./version-metadata.json

    - uses: actions/upload-artifact@v3
      with:
        path: web-ext-artifacts/new_tab_moment-${{ github.ref_name }}.xpi
        if-no-files-found: error

    outputs:
      release_notes: ${{ steps.extract-release-notes.outputs.release_notes }}

  release-github:
    needs: [release-firefox]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3

      - name: Display structure of downloaded files
        run: ls -R

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: ${{ github.ref_name }}
          body: ${{ needs.release-firefox.outputs.release_notes }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            artifact/new_tab_-_moment-${{ github.ref_name }}.zip
            artifact/new_tab_moment-${{ github.ref_name }}.xpi

  release-edge:
    needs: [release-firefox]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3

      - name: Display structure of downloaded files
        run: ls -R

      - name: Upload draft
        run: |
          token=$(curl -X POST -H "Content-Type: application/x-www-form-urlencoded" -d "client_id=${{ secrets.EDGE_CLIENT }}" -d "scope=https://api.addons.microsoftedge.microsoft.com/.default" -d "client_secret=${{ secrets.EDGE_SECRET }}" -d "grant_type=client_credentials" -v ${{ secrets.EDGE_TOKEN_URL }} | jq --raw-output '.access_token')
          curl -H "Authorization: Bearer ${token}" -H "Content-Type: application/zip" -X POST -T artifact/new_tab_-_moment-${{ github.ref_name }}.zip -v https://api.addons.microsoftedge.microsoft.com/v1/products/${{ secrets.EDGE_PRODUCT }}/submissions/draft/package
        # wait for the upload to complete and publish
